[profile.default]
src = 'contracts'
out = 'out'
libs = [
  'lib',
  'node_modules'
]
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20_000

remappings = [
    'forge-std/=lib/forge-std/src/'
]
