name: Publish to Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Copy Readme and Changelog
        run: |
          cp README.md docs
          cp CHANGELOG.md docs
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          target-directory: 'docs/developers/identity-contracts'
          destination-github-username: 'masa-finance'
          destination-repository-name: 'docs'
          user-email: 13647606+H34D@users.noreply.github.com
          target-branch: main
