name: Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: node:latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn compile
      - run: sleep 10
      - run: yarn test
        env:
          ANKR_API_KEY: ${{ secrets.ANKR_API_KEY }}
