name: Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '18'
      - run: yarn
      - run: yarn compile
      - run: sleep 10
      - run: yarn test
        env:
          ANKR_API_KEY: ${{ secrets.ANKR_API_KEY }}
        id: test
