name: Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
